import = ["~/.config/alacritty/themes/github-light.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 15

[font.glyph_offset]
x = 0
y = 7

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "¬"
key = "}"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "˙"
key = "{"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "ç"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "≈"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "⌟"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "«"
key = "Backslash"
mods = "Command"

[[keyboard.bindings]]
chars = "‘"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "÷"
key = "R"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_padding = true

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-l", "-c", "tmux attach -t home || tmux new-session -s home"]

[window.padding]
x = 14
y = 10
