# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showFileTree: false
  showRootItemInFileTree: false
