# (Github Light) Colors for Wezterm

[colors]
background = '#ffffff'
foreground = '#1F2328'

cursor_bg = '#bbdfff'
cursor_border = '#1F2328'
cursor_fg = '#1F2328'

selection_bg = '#bbdfff'
selection_fg = '#1F2328'

ansi = [
  '#24292f',
  '#cf222e',
  '#116329',
  '#4d2d00',
  '#0969da',
  '#8250df',
  '#1b7c83',
  '#6e7781',
]
brights = [
  '#57606a',
  '#a40e26',
  '#1a7f37',
  '#633c01',
  '#218bff',
  '#a475f9',
  '#3192aa',
  '#8c959f',
]

[colors.tab_bar]
background = '#ffffff'

[colors.tab_bar.active_tab]
bg_color = '#0969da'
fg_color = '#ffffff'

[colors.tab_bar.inactive_tab]
bg_color = '#f1f1f1'
fg_color = '#b1bac4'

[colors.tab_bar.new_tab]
bg_color = '#efefef'
fg_color = '#b1bac4'
