# (Github Light Tritanopia) Colors for Wezterm

[colors]
background = '#ffffff'
foreground = '#24292f'

cursor_bg = '#24292f'
cursor_border = '#24292f'
cursor_fg = '#ffffff'

selection_bg = '#bbdfff'
selection_fg = '#24292f'

ansi = [
    '#24292f',
    '#cf222e',
    '#0550ae',
    '#4d2d00',
    '#0969da',
    '#8250df',
    '#1b7c83',
    '#6e7781',
]
brights = [
    '#57606a',
    '#a40e26',
    '#0969da',
    '#633c01',
    '#218bff',
    '#a475f9',
    '#3192aa',
    '#8c959f',
]