#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(find ~/Code ~/Code/lrn ~/Code/shift ~/.config ~ -type d -mindepth 1 -maxdepth 1 | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  # Create new session with first window named "editor" and start nvim
  tmux new-session -s $selected_name -c $selected -n editor "nvim; fish"
  # Create second window named "server"
  tmux new-window -t $selected_name: -c $selected -n server
  # Create third window named "shell"
  tmux new-window -t $selected_name: -c $selected -n shell
  # Select the first window (editor)
  tmux select-window -t $selected_name:editor
  exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  # Create new detached session with first window named "editor" and start nvim
  tmux new-session -ds $selected_name -c $selected -n editor "nvim; bash"
  # Create second window named "server"
  tmux new-window -t $selected_name: -c $selected -n server
  # Create third window named "shell"
  tmux new-window -t $selected_name: -c $selected -n shell
  # Select the first window (editor)
  tmux select-window -t $selected_name:editor
fi

tmux switch-client -t $selected_name
